### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by MozamelJawad** [MozamelJawad/Recipe-app#13]
**Hi Reviewer 👋**

We have created the issues and tasks are assigned to each person on the team for this [Project ](https://github.com/users/MozamelJawad/projects/7/views/2)
In this team we are two working on this project:

1. Person A: @SaveryIV 
2. Person B: @MozamelJawad

**Comment by Ibizugbe** [comment]
Hi @MozamelJawad  @SaveryIV 👋🏼👋🏼👋🏼, 

![approved](https://github.com/MozamelJawad/Recipe-app/assets/64643995/fb332ff6-745e-4078-90ef-c36a4787d259)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] Points are fairly distributed amongst team members👍🏼.
- [x] The required columns have been added to the kanban board👍🏼.
- [x] The requirements for the project are captured in the kanban board👍🏼.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MozamelJawad** [comment]
Thanks for your review.
